name: cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'

      - name: install yarn
        # avoid checksum errors with github packages
        run: YARN_CHECKSUM_BEHAVIOR=update yarn

      - name: cypress run
        uses: cypress-io/github-action@v2
        env:
          NEXT_PUBLIC_API_HOST: https://graasp.eu
          NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: G-H48F1X7SWK
          NEXT_PUBLIC_PUBLISHED_TAG_ID: ea9a3b4e-7b67-44c2-a9df-528b6ae5424f
          PORT: 3005
          NEXT_PUBLIC_API_HOST: http://localhost:3000
          NEXT_PUBLIC_GRAASP_AUTH_HOST: http://localhost:3001
          NEXT_PUBLIC_GRAASP_PERFORM_HOST: http://localhost:3112
          GRAASPER_ID: e890a236-3d45-4042-8a95-c91120f4db73
          NEXT_PUBLIC_NODE_ENV: test
        with:
          install: false
          config: baseUrl=http://localhost:3005
          start: yarn start:ci
          wait-on: 'http://localhost:3005'
          wait-on-timeout: 180
          browser: chrome
          headless: true
          quiet: true

      - name: coverage report
        run: npx nyc report --reporter=text-summary
